use PF_DB;
insert into labels (label, transaction_type, category) values ('Salary', 'Income', 'Income');
insert into labels (label, transaction_type, category) values ('Bonus & Holiday Allowance', 'Income', 'Income');
insert into labels (label, transaction_type, category) values ('Home & Health Allowance', 'Income', 'Income');
insert into labels (label, transaction_type, category) values ('Sold Stuff', 'Income', 'Income');
insert into labels (label, transaction_type, category) values ('Rent', 'Expenses', 'Home');
insert into labels (label, transaction_type, category) values ('Home Insurance', 'Expenses', 'Home');
insert into labels (label, transaction_type, category) values ('Gas & Electricity', 'Expenses', 'Home');
insert into labels (label, transaction_type, category) values ('Water', 'Expenses', 'Home');
insert into labels (label, transaction_type, category) values ('Internet', 'Expenses', 'Home');
insert into labels (label, transaction_type, category) values ('Household Repairs', 'Expenses', 'Home');
insert into labels (label, transaction_type, category) values ('Others', 'Expenses', 'Home');
insert into labels (label, transaction_type, category) values ('Health Insurance', 'Expenses', 'Medical');
insert into labels (label, transaction_type, category) values ('Primary Care & Medication', 'Expenses', 'Medical');
insert into labels (label, transaction_type, category) values ('Dental Care', 'Expenses', 'Medical');
insert into labels (label, transaction_type, category) values ('Grocery', 'Expenses', 'Food');
insert into labels (label, transaction_type, category) values ('Restaurants', 'Expenses', 'Food');
insert into labels (label, transaction_type, category) values ('Public Transport', 'Expenses', 'Transportation');
insert into labels (label, transaction_type, category) values ('Gasoline', 'Expenses', 'Transportation');
insert into labels (label, transaction_type, category) values ('Car Insurance', 'Expenses', 'Transportation');
insert into labels (label, transaction_type, category) values ('Maintenance & Repair', 'Expenses', 'Transportation');
insert into labels (label, transaction_type, category) values ('Parking Fees', 'Expenses', 'Transportation');
insert into labels (label, transaction_type, category) values ('Car Payments', 'Expenses', 'Transportation');
insert into labels (label, transaction_type, category) values ('Bank Fee', 'Expenses', 'Financial');
insert into labels (label, transaction_type, category) values ('Income Tax', 'Expenses', 'Financial');
insert into labels (label, transaction_type, category) values ('Allowance Pay Back', 'Expenses', 'Financial');
insert into labels (label, transaction_type, category) values ('Movies & Books', 'Expenses', 'Entertainment');
insert into labels (label, transaction_type, category) values ('Tv & Streaming', 'Expenses', 'Entertainment');
insert into labels (label, transaction_type, category) values ('Events & Vacation', 'Expenses', 'Entertainment');
insert into labels (label, transaction_type, category) values ('Hobbies', 'Expenses', 'Entertainment');
insert into labels (label, transaction_type, category) values ('Clothing & Accesories', 'Expenses', 'Shopping');
insert into labels (label, transaction_type, category) values ('Electronics & Software', 'Expenses', 'Shopping');
insert into labels (label, transaction_type, category) values ('Home Decor & Furnishings', 'Expenses', 'Shopping');
insert into labels (label, transaction_type, category) values ('Gifts', 'Expenses', 'Shopping');
insert into labels (label, transaction_type, category) values ('Cell Phone', 'Expenses', 'Personal');
insert into labels (label, transaction_type, category) values ('Haircuts & Cosmetics', 'Expenses', 'Personal');
insert into labels (label, transaction_type, category) values ('Self Care', 'Expenses', 'Personal');
insert into labels (label, transaction_type, category) values ('Education', 'Expenses', 'Personal Investment');
insert into labels (label, transaction_type, category) values ('Loan Payments', 'Expenses', 'Personal Investment');
insert into labels (label, transaction_type, category) values ('Emergency Fund', 'Savings', 'Savings');	
insert into labels (label, transaction_type, category) values ('Education Fund', 'Savings', 'Savings');
insert into labels (label, transaction_type, category) values ('Vacation Fund', 'Savings', 'Savings');
insert into labels (label, transaction_type, category) values ('Car Fund', 'Savings', 'Savings');
insert into labels (label, transaction_type, category) values ('Repayment Fund', 'Savings', 'Savings');
insert into labels (label, transaction_type, category) values ('Software Fund', 'Savings', 'Savings');
insert into labels (label, transaction_type, category) values ('Babe Fund', 'Savings', 'Savings');
insert into labels (label, transaction_type, category) values ('Mayleigh Fund', 'Savings', 'Savings');
commit;